version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ./rabbitmq/dados/:/var/lib/rabbitmq/
        - ./rabbitmq/log/:/var/log/rabbitmq
    environment:
        - RABBITMQ_DEFAULT_USER=admin
        - RABBITMQ_DEFAULT_PASS=senha