spring:
  application:
    name: san-login
  profiles:
    active: usage_message    
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: senha
    

server:
  port: 8090   

eureka:
 client:
   serviceUrl:
     defaultZone: http://localhost:8761/eureka/
     
