spring:
  application:
    name: san-admin
  datasource:
    password: ${DATABASE_PASSWORD}
    url: jdbc:postgresql://localhost:5432/san-admin
    username: msansone
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

#  security:
#    user:
#      name: admin
#      password: ${SECURITY_PASSWORD}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/