spring:
  application:
    name: san-admin
  datasource:
    password: ${DATABASE_PASSWORD}
    url: jdbc:postgresql://localhost:5432/san-admin
    username: msansone
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

<<<<<<< HEAD
#  security:
#    user:
#      name: admin
#      password: ${SECURITY_PASSWORD}
=======
  security:
    user:
      name: admin
      password: ${SECURITY_PASSWORD}
>>>>>>> e030a4be26598829b1d7de59b3d9d71d776d2c94

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/